/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugbes_pbo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; // Ini penting untuk tabel
import javax.swing.JButton; // Untuk tombol di tabel
import javax.swing.table.TableCellRenderer; // Untuk membuat tombol terlihat
import javax.swing.table.TableCellEditor; // Untuk membuat tombol berfungsi
import java.awt.Component; // Untuk Cell Renderer/Editor
import java.awt.event.ActionEvent; // Untuk aksi tombol
import java.awt.event.ActionListener; // Untuk aksi tombol
import java.io.File; // Untuk membuka file
import java.awt.Desktop; // Untuk membuka file
import java.sql.Date;

/**
 *
 * @author nasyihulwan
 */
public class DashboardMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form DashboardMahasiswa
     */
    public DashboardMahasiswa() {
        initComponents();
        // --- BAGIAN PENTING: Mengambil dan Menampilkan Data Sesi ---
        UserSession session = UserSession.getInstance();

        // Memastikan data sesi ada sebelum menampilkannya
        if (session.isLoggedIn() && session.getNim() != null && session.getNama() != null) {
            // Set teks pada JLabel dengan data dari sesi
            nim.setText("NIM: " + session.getNim());
            namaMahasiswa.setText("Nama: " + session.getNama());
            loadHistoriAspirasi(session.getNim());
        } else {
            // Opsional: Tampilkan pesan atau lakukan sesuatu jika sesi tidak valid
            System.out.println("Sesi mahasiswa tidak ditemukan atau tidak lengkap.");
            // nim.setText("NIM: -"); // Fallback
            // namaMahasiswa.setText("Nama: -"); // Fallback
            JOptionPane.showMessageDialog(this, "Sesi login tidak valid. Silakan login kembali.", "Error Sesi", JOptionPane.ERROR_MESSAGE);
            // Redirect kembali ke halaman login jika sesi tidak valid
            new DashboardLogin().setVisible(true);
            this.dispose(); // Tutup dashboard mahasiswa
        }
    }
    
    private void loadHistoriAspirasi(String nimMahasiswa) {
        DefaultTableModel model = (DefaultTableModel) tabelHistoriAspirasi.getModel();
        model.setRowCount(0); // Hapus semua baris yang ada di tabel

        String query = "SELECT id_aspirasi, tgl_aspirasi, judul_aspirasi, status " +
                       "FROM aspirasi WHERE nim = ? ORDER BY tgl_aspirasi DESC"; // Urutkan berdasarkan tanggal terbaru

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ruangaspira", "root", "");
             PreparedStatement pstmt = conn.prepareStatement(query)) {

            pstmt.setString(1, nimMahasiswa); // Set NIM mahasiswa yang login
            try (ResultSet rs = pstmt.executeQuery()) {
                int no = 1;
                while (rs.next()) {
                    String idAspirasi = rs.getString("id_aspirasi");
                    Date tglPengaduan = rs.getDate("tgl_aspirasi"); // Ambil sebagai java.sql.Date
                    String judulAspirasi = rs.getString("judul_aspirasi");
                    String status = rs.getString("status");

                    // Tambahkan baris ke model tabel
                    model.addRow(new Object[]{
                        no++,
                        idAspirasi,
                        tglPengaduan,
                        judulAspirasi,
                        status
                    });
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error mengambil data histori aspirasi: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaMahasiswa = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        buatAspirasi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHistoriAspirasi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namaMahasiswa.setText("Nama");

        nim.setText("NIM");

        buatAspirasi.setText("Buat Aspirasi");
        buatAspirasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatAspirasiActionPerformed(evt);
            }
        });

        tabelHistoriAspirasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID Aspirasi", "Tanggal Pengaduan", "Judul Laporan", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelHistoriAspirasi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buatAspirasi)
                    .addComponent(nim)
                    .addComponent(namaMahasiswa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(namaMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nim)
                .addGap(18, 18, 18)
                .addComponent(buatAspirasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buatAspirasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatAspirasiActionPerformed
        InputAspirasi inputAspirasiForm = new InputAspirasi();
        inputAspirasiForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buatAspirasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatAspirasi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaMahasiswa;
    private javax.swing.JLabel nim;
    private javax.swing.JTable tabelHistoriAspirasi;
    // End of variables declaration//GEN-END:variables
}
