package com.mycompany.tugbes_pbo;

import com.mycompany.tugbes_pbo.DashboardPetugas;
import com.mycompany.tugbes_pbo.DashboardMahasiswa;
import at.favre.lib.crypto.bcrypt.BCrypt;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nasyihulwan
 */
public class DashboardLogin extends javax.swing.JFrame {

    /**
     * Creates new form HelloGUI
     */
    public DashboardLogin() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(9,31,64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Password");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Username");

        btnLogin.setText("Masuk");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogin)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(inputUser)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel3)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String username = inputUser.getText();
    String password = inputPassword.getText();

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ruangaspira", "root", "")) {
        // Cek di tabel petugas
        // Pastikan Anda mengambil semua kolom yang diperlukan (id_petugas, nama_petugas, level, password)
        String queryPetugas = "SELECT id_petugas, nama_petugas, level, password FROM petugas WHERE username = ?";
        try (PreparedStatement stmtPetugas = conn.prepareStatement(queryPetugas)) {
            stmtPetugas.setString(1, username);
            try (ResultSet rsPetugas = stmtPetugas.executeQuery()) {
                if (rsPetugas.next()) {
                    String hashedPassword = rsPetugas.getString("password");
                    BCrypt.Result result = BCrypt.verifyer().verify(password.toCharArray(), hashedPassword);

                    if (result.verified) {
                        // --- BAGIAN PENTING: SET DATA SESI UNTUK PETUGAS ---
                        UserSession session = UserSession.getInstance();
                        session.setUsername(username);
                        session.setIdPetugas(rsPetugas.getString("id_petugas"));
                        session.setNama(rsPetugas.getString("nama_petugas"));
                        session.setLevel(rsPetugas.getString("level"));
                        // --------------------------------------------------

                        JOptionPane.showMessageDialog(this, "Login sebagai Petugas berhasil!");
                        this.setVisible(false); // Sembunyikan jendela login
                        new DashboardPetugas().setVisible(true); // Tampilkan dashboard petugas
                        return; // Keluar dari metode setelah login berhasil
                    } else {
                        JOptionPane.showMessageDialog(this, "Password salah untuk akun Petugas!");
                        return; // Keluar jika password salah
                    }
                }
            }
        }

        // Jika tidak ditemukan di petugas, cek di mahasiswa
        // Pastikan Anda mengambil semua kolom yang diperlukan (nim, nama, password)
        String queryMahasiswa = "SELECT nim, nama, password FROM mahasiswa WHERE username = ?";
        try (PreparedStatement stmtMahasiswa = conn.prepareStatement(queryMahasiswa)) {
            stmtMahasiswa.setString(1, username);
            try (ResultSet rsMahasiswa = stmtMahasiswa.executeQuery()) {
                if (rsMahasiswa.next()) {
                    String hashedPassword = rsMahasiswa.getString("password");
                    BCrypt.Result result = BCrypt.verifyer().verify(password.toCharArray(), hashedPassword);

                    if (result.verified) {
                        // --- BAGIAN PENTING: SET DATA SESI UNTUK MAHASISWA ---
                        UserSession session = UserSession.getInstance();
                        session.setUsername(username);
                        session.setNim(rsMahasiswa.getString("nim"));
                        session.setNama(rsMahasiswa.getString("nama"));
                        // ----------------------------------------------------

                        JOptionPane.showMessageDialog(this, "Login sebagai Mahasiswa berhasil!");
                        this.setVisible(false); // Sembunyikan jendela login
                        new DashboardMahasiswa().setVisible(true); // Tampilkan dashboard mahasiswa
                    } else {
                        JOptionPane.showMessageDialog(this, "Password salah untuk akun Mahasiswa!");
                    }
                } else {
                    // Jika tidak ditemukan di kedua tabel
                    JOptionPane.showMessageDialog(this, "Username tidak ditemukan!");
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace(); // Cetak stack trace untuk debugging
        JOptionPane.showMessageDialog(this, "Kesalahan Database: " + e.getMessage() + "\nPastikan XAMPP/MySQL berjalan dan database 'ruangaspira' terhubung dengan benar.");
    } catch (Exception e) {
        e.printStackTrace(); // Cetak stack trace untuk debugging
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan tak terduga: " + e.getMessage());
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
